services:
  bot:
    build: .
    image: hangbot-ps-one-guild
    restart: always
    env_file: ./.env
    depends_on:
      database:
        condition: service_healthy
        restart: true

  # This must be the same name as `PGHOST` in `.env`.
  database:
    image: postgres
    restart: always
    ports:
      - ${PGPORT}:5432
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_DB: ${PGDATABASE}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PGUSER} -d ${PGDATABASE}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  # database visualization tool
  adminer:
    image: adminer
    restart: always
    ports:
      - 6969:8080
